name: musilingo
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependências existentes
  supabase_flutter: ^2.9.1
  provider: ^6.1.5
  just_audio: ^0.9.46
  flutter_midi: ^1.1.0
  flutter_sound: ^9.28.0
  fftea: ^1.5.0
  pitch_detector_dart: ^0.0.7
  speech_to_text: ^7.3.0
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.0.0
  permission_handler: ^11.4.0
  record: ^6.1.1
  path_provider: ^2.1.3
  webview_flutter: ^4.9.0
  webview_flutter_android: ^3.16.9
  webview_flutter_wkwebview: ^3.23.0
  collection: ^1.18.0
  rxdart: ^0.27.7
  shared_preferences: ^2.5.3
  confetti: ^0.8.0
  smooth_page_indicator: ^1.2.1
  flutter_midi_pro: ^3.1.4
  flutter_svg: ^2.0.10+1
  drag_and_drop_lists: ^0.4.2
  image_picker: ^1.2.0
  flutter_dotenv: ^6.0.0
  google_fonts: ^6.3.0
  intl: ^0.19.0
  flutter_riverpod: ^2.6.1
  http: ^1.5.0
  flutter_bloc: ^9.1.1
  hive_flutter: ^1.1.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1
  verovio_flutter:
    path: ./verovio_flutter
  flutter_widget_from_html: ^0.16.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.9
  supabase: ^2.1.2
  yaml: ^3.1.2

# A seção flutter é o local correto para 'uses-material-design' e 'assets'
flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/sf2/GeneralUserGS.sf2
    - assets/audio/
    - assets/osmd_viewer/ 
    - assets/osmd_viewer/js/

# Esta seção força o Flutter a usar sua versão local do verovio
dependency_overrides:
  verovio_flutter:
    path: ./verovio_flutter