-- ==========================================
-- Exercícios de Solfejo Expandidos para Sistema Robusto
-- ==========================================

-- Limpar exercícios existentes (opcional)
-- DELETE FROM public.practice_solfege;

-- ==========================================
-- NÍVEL BÁSICO (1-20) - 4 Compassos cada
-- ==========================================

INSERT INTO public.practice_solfege (id, title, difficulty_level, difficulty_value, key_signature, time_signature, tempo, note_sequence, clef) VALUES

-- Intervalos de 2ª - 4 compassos cada
(1, 'Intervalo de 2ª Maior (Dó-Ré)', 'basico', 1, 'C', '4/4', 60, '[{"note":"C4","lyric":"Dó","duration":"half"},{"note":"D4","lyric":"Ré","duration":"half"},{"note":"C4","lyric":"Dó","duration":"half"},{"note":"D4","lyric":"Ré","duration":"half"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"half"},{"note":"C4","lyric":"Dó","duration":"half"},{"note":"D4","lyric":"Ré","duration":"half"},{"note":"C4","lyric":"Dó","duration":"half"},{"note":"C4","lyric":"Dó","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"}]', 'treble'),

(2, 'Intervalo de 2ª com Variações', 'basico', 2, 'C', '4/4', 65, '[{"note":"D4","lyric":"Ré","duration":"half"},{"note":"E4","lyric":"Mi","duration":"half"},{"note":"D4","lyric":"Ré","duration":"half"},{"note":"E4","lyric":"Mi","duration":"half"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"half"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"half"},{"note":"D4","lyric":"Ré","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"}]', 'treble'),

(3, 'Intervalo de 2ª Menor (Mi-Fá)', 'basico', 3, 'C', '4/4', 65, '[{"note":"E4","lyric":"Mi","duration":"half"},{"note":"F4","lyric":"Fá","duration":"half"},{"note":"E4","lyric":"Mi","duration":"half"},{"note":"F4","lyric":"Fá","duration":"half"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"half"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"half"},{"note":"E4","lyric":"Mi","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"}]', 'treble'),

-- Intervalos de 3ª - 4 compassos cada
(4, 'Intervalo de 3ª Maior (Dó-Mi)', 'basico', 4, 'C', '4/4', 70, '[{"note":"C4","lyric":"Dó","duration":"half"},{"note":"E4","lyric":"Mi","duration":"half"},{"note":"C4","lyric":"Dó","duration":"half"},{"note":"E4","lyric":"Mi","duration":"half"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"}]', 'treble'),

(5, 'Intervalo de 3ª Menor (Ré-Fá)', 'basico', 5, 'C', '4/4', 70, '[{"note":"D4","lyric":"Ré","duration":"half"},{"note":"F4","lyric":"Fá","duration":"half"},{"note":"D4","lyric":"Ré","duration":"half"},{"note":"F4","lyric":"Fá","duration":"half"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"}]', 'treble'),

-- Intervalos de 4ª e 5ª
(6, 'Intervalo de 4ª Justa (Dó-Fá)', 'basico', 6, 'C', '4/4', 75, '[{"note":"C4","lyric":"Dó","duration":"half"},{"note":"F4","lyric":"Fá","duration":"half"},{"note":"C4","lyric":"Dó","duration":"half"},{"note":"F4","lyric":"Fá","duration":"half"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"}]', 'treble'),

(7, 'Intervalo de 5ª Justa (Dó-Sol)', 'basico', 7, 'C', '4/4', 75, '[{"note":"C4","lyric":"Dó","duration":"half"},{"note":"G4","lyric":"Sol","duration":"half"},{"note":"C4","lyric":"Dó","duration":"half"},{"note":"G4","lyric":"Sol","duration":"half"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"}]', 'treble'),

-- Tríades básicas - 4 compassos
(8, 'Tríade de Dó Maior', 'basico', 8, 'C', '4/4', 80, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"}]', 'treble'),

(9, 'Tríade de Fá Maior', 'basico', 9, 'C', '4/4', 80, '[{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"F5","lyric":"Fá","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"F5","lyric":"Fá","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"}]', 'treble'),

(10, 'Tríade de Sol Maior', 'basico', 10, 'C', '4/4', 80, '[{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"G5","lyric":"Sol","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"G5","lyric":"Sol","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"}]', 'treble'),

-- Fragmentos de escala - 4 compassos
(11, 'Pentacorde de Dó (Dó-Sol)', 'basico', 11, 'C', '4/4', 90, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"}]', 'treble'),

(12, 'Graus I-V-I com Passagem', 'basico', 12, 'C', '4/4', 85, '[{"note":"C4","lyric":"Dó","duration":"half"},{"note":"G4","lyric":"Sol","duration":"half"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"}]', 'treble'),

-- Saltos básicos - 4 compassos
(13, 'Saltos de 3ª e 5ª', 'basico', 13, 'C', '4/4', 80, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"}]', 'treble'),

(14, 'Salto de Oitava com Passagem', 'basico', 14, 'C', '4/4', 75, '[{"note":"C4","lyric":"Dó","duration":"half"},{"note":"C5","lyric":"Dó","duration":"half"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"}]', 'treble'),

-- Padrões de repetição - 4 compassos
(15, 'Padrão Ascendente por Graus', 'basico', 15, 'C', '4/4', 90, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"}]', 'treble'),

(16, 'Padrão de Terças Ascendentes', 'basico', 16, 'C', '4/4', 85, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"}]', 'treble'),

(17, 'Movimento Ondulado', 'basico', 17, 'C', '4/4', 85, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"}]', 'treble'),

(18, 'Arpejo com Retorno', 'basico', 18, 'C', '4/4', 80, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"half"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"}]', 'treble'),

(19, 'Graus Conjuntos e Disjuntos', 'basico', 19, 'C', '4/4', 85, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"},{"note":"rest","duration":"whole"}]', 'treble'),

(20, 'Revisão dos Intervalos Básicos', 'basico', 20, 'C', '4/4', 80, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"half"},{"note":"rest","duration":"whole"}]', 'treble'),

-- ==========================================
-- NÍVEL INICIANTE (21-40) - 6-8 Compassos cada
-- ==========================================

-- Escalas completas em diferentes tons - 6 compassos
(21, 'Escala de Dó Maior Completa', 'iniciante', 1, 'C', '4/4', 100, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"half"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"},{"note":"rest","duration":"whole"}]', 'treble'),
(22, 'Escala de Sol Maior', 'iniciante', 2, 'G', '4/4', 120, '[{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"A4","lyric":"Lá","duration":"eighth"},{"note":"B4","lyric":"Si","duration":"eighth"},{"note":"C5","lyric":"Dó","duration":"eighth"},{"note":"D5","lyric":"Ré","duration":"eighth"},{"note":"E5","lyric":"Mi","duration":"eighth"},{"note":"F#5","lyric":"Fá#","duration":"eighth"},{"note":"G5","lyric":"Sol","duration":"quarter"}]', 'treble'),
(23, 'Escala de Fá Maior', 'iniciante', 3, 'F', '4/4', 120, '[{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"A4","lyric":"Lá","duration":"eighth"},{"note":"Bb4","lyric":"Sib","duration":"eighth"},{"note":"C5","lyric":"Dó","duration":"eighth"},{"note":"D5","lyric":"Ré","duration":"eighth"},{"note":"E5","lyric":"Mi","duration":"eighth"},{"note":"F5","lyric":"Fá","duration":"quarter"}]', 'treble'),

-- Arpejos em diferentes tons
(24, 'Arpejo de Sol Maior', 'iniciante', 4, 'G', '4/4', 100, '[{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"G5","lyric":"Sol","duration":"quarter"}]', 'treble'),
(25, 'Arpejo de Fá Maior', 'iniciante', 5, 'F', '4/4', 100, '[{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"F5","lyric":"Fá","duration":"quarter"}]', 'treble'),

-- Progressões harmônicas básicas
(26, 'Progressão I-V-I (Dó-Sol-Dó)', 'iniciante', 6, 'C', '4/4', 90, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"}]', 'treble'),

-- Exercícios rítmicos
(27, 'Ritmo de Colcheias', 'iniciante', 7, 'C', '4/4', 110, '[{"note":"C4","lyric":"Dó","duration":"eighth"},{"note":"D4","lyric":"Ré","duration":"eighth"},{"note":"E4","lyric":"Mi","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"E4","lyric":"Mi","duration":"eighth"},{"note":"D4","lyric":"Ré","duration":"eighth"}]', 'treble'),
(28, 'Ritmo Pontuado', 'iniciante', 8, 'C', '4/4', 100, '[{"note":"C4","lyric":"Dó","duration":"dotted-quarter"},{"note":"D4","lyric":"Ré","duration":"eighth"},{"note":"E4","lyric":"Mi","duration":"dotted-quarter"},{"note":"F4","lyric":"Fá","duration":"eighth"}]', 'treble'),

-- Intervalos compostos
(29, 'Intervalos de 6ª', 'iniciante', 9, 'C', '4/4', 80, '[{"note":"C4","lyric":"Dó","duration":"half"},{"note":"A4","lyric":"Lá","duration":"half"},{"note":"D4","lyric":"Ré","duration":"half"},{"note":"B4","lyric":"Si","duration":"half"}]', 'treble'),
(30, 'Intervalos de 7ª', 'iniciante', 10, 'C', '4/4', 80, '[{"note":"C4","lyric":"Dó","duration":"half"},{"note":"B4","lyric":"Si","duration":"half"},{"note":"F4","lyric":"Fá","duration":"half"},{"note":"E5","lyric":"Mi","duration":"half"}]', 'treble'),

-- Continuação para exercícios 31-40 com mais variedade...
(31, 'Sequência Escalar Mista', 'iniciante', 11, 'C', '4/4', 130, '[{"note":"C4","lyric":"Dó","duration":"eighth"},{"note":"E4","lyric":"Mi","duration":"eighth"},{"note":"D4","lyric":"Ré","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"E4","lyric":"Mi","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"A4","lyric":"Lá","duration":"eighth"}]', 'treble'),
(32, 'Arpejo Menor (Lá menor)', 'iniciante', 12, 'C', '4/4', 100, '[{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"E5","lyric":"Mi","duration":"quarter"},{"note":"A5","lyric":"Lá","duration":"quarter"}]', 'treble'),

-- ==========================================
-- NÍVEL INTERMEDIÁRIO (41-80) - Complexidade Crescente
-- ==========================================

-- Escalas menores
(41, 'Escala de Lá Menor Natural', 'intermediário', 1, 'Am', '4/4', 120, '[{"note":"A4","lyric":"Lá","duration":"eighth"},{"note":"B4","lyric":"Si","duration":"eighth"},{"note":"C5","lyric":"Dó","duration":"eighth"},{"note":"D5","lyric":"Ré","duration":"eighth"},{"note":"E5","lyric":"Mi","duration":"eighth"},{"note":"F5","lyric":"Fá","duration":"eighth"},{"note":"G5","lyric":"Sol","duration":"eighth"},{"note":"A5","lyric":"Lá","duration":"quarter"}]', 'treble'),
(42, 'Escala de Ré Menor', 'intermediário', 2, 'Dm', '4/4', 120, '[{"note":"D4","lyric":"Ré","duration":"eighth"},{"note":"E4","lyric":"Mi","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"A4","lyric":"Lá","duration":"eighth"},{"note":"Bb4","lyric":"Sib","duration":"eighth"},{"note":"C5","lyric":"Dó","duration":"eighth"},{"note":"D5","lyric":"Ré","duration":"quarter"}]', 'treble'),

-- Escalas cromáticas parciais
(43, 'Cromatismo Ascendente (Dó-Sol)', 'intermediário', 3, 'C', '4/4', 110, '[{"note":"C4","lyric":"Dó","duration":"16th"},{"note":"C#4","lyric":"Dó#","duration":"16th"},{"note":"D4","lyric":"Ré","duration":"16th"},{"note":"D#4","lyric":"Ré#","duration":"16th"},{"note":"E4","lyric":"Mi","duration":"16th"},{"note":"F4","lyric":"Fá","duration":"16th"},{"note":"F#4","lyric":"Fá#","duration":"16th"},{"note":"G4","lyric":"Sol","duration":"eighth"}]', 'treble'),

-- Modulações simples
(44, 'Modulação Dó-Sol Maior', 'intermediário', 4, 'C', '4/4', 100, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F#4","lyric":"Fá#","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"}]', 'treble'),

-- Saltos grandes
(45, 'Saltos de Oitava Múltiplos', 'intermediário', 5, 'C', '4/4', 90, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"E5","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"G5","lyric":"Sol","duration":"quarter"}]', 'treble'),

-- Exercícios em compassos compostos
(46, 'Exercício em 6/8', 'intermediário', 6, 'C', '6/8', 120, '[{"note":"C4","lyric":"Dó","duration":"eighth"},{"note":"D4","lyric":"Ré","duration":"eighth"},{"note":"E4","lyric":"Mi","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"A4","lyric":"Lá","duration":"eighth"}]', 'treble'),
(47, 'Exercício em 3/4', 'intermediário', 7, 'C', '3/4', 100, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"}]', 'treble'),

-- Continuação para mais exercícios intermediários...
(48, 'Sequência de Tríades', 'intermediário', 8, 'C', '4/4', 110, '[{"note":"C4","lyric":"Dó","duration":"eighth"},{"note":"E4","lyric":"Mi","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"A4","lyric":"Lá","duration":"eighth"},{"note":"C5","lyric":"Dó","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"B4","lyric":"Si","duration":"eighth"}]', 'treble'),

-- ==========================================
-- NÍVEL AVANÇADO (81-120) - Desafios Complexos
-- ==========================================

-- Escalas exóticas e modos
(81, 'Modo Dórico (Ré-Ré)', 'avançado', 1, 'C', '4/4', 130, '[{"note":"D4","lyric":"Ré","duration":"eighth"},{"note":"E4","lyric":"Mi","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"A4","lyric":"Lá","duration":"eighth"},{"note":"B4","lyric":"Si","duration":"eighth"},{"note":"C5","lyric":"Dó","duration":"eighth"},{"note":"D5","lyric":"Ré","duration":"quarter"}]', 'treble'),
(82, 'Modo Frígio (Mi-Mi)', 'avançado', 2, 'C', '4/4', 130, '[{"note":"E4","lyric":"Mi","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"A4","lyric":"Lá","duration":"eighth"},{"note":"B4","lyric":"Si","duration":"eighth"},{"note":"C5","lyric":"Dó","duration":"eighth"},{"note":"D5","lyric":"Ré","duration":"eighth"},{"note":"E5","lyric":"Mi","duration":"quarter"}]', 'treble'),

-- Escalas cromáticas completas
(83, 'Escala Cromática Completa', 'avançado', 3, 'C', '4/4', 140, '[{"note":"C4","lyric":"Dó","duration":"16th"},{"note":"C#4","lyric":"Dó#","duration":"16th"},{"note":"D4","lyric":"Ré","duration":"16th"},{"note":"D#4","lyric":"Ré#","duration":"16th"},{"note":"E4","lyric":"Mi","duration":"16th"},{"note":"F4","lyric":"Fá","duration":"16th"},{"note":"F#4","lyric":"Fá#","duration":"16th"},{"note":"G4","lyric":"Sol","duration":"16th"},{"note":"G#4","lyric":"Sol#","duration":"16th"},{"note":"A4","lyric":"Lá","duration":"16th"},{"note":"A#4","lyric":"Lá#","duration":"16th"},{"note":"B4","lyric":"Si","duration":"16th"},{"note":"C5","lyric":"Dó","duration":"eighth"}]', 'treble'),

-- Intervalos complexos e dissonantes
(84, 'Intervalos de 2ª Menor Consecutivos', 'avançado', 4, 'C', '4/4', 100, '[{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"}]', 'treble'),

-- Modulações complexas
(85, 'Modulação por Tons Inteiros', 'avançado', 5, 'C', '4/4', 120, '[{"note":"C4","lyric":"Dó","duration":"eighth"},{"note":"D4","lyric":"Ré","duration":"eighth"},{"note":"E4","lyric":"Mi","duration":"eighth"},{"note":"F#4","lyric":"Fá#","duration":"eighth"},{"note":"G#4","lyric":"Sol#","duration":"eighth"},{"note":"A#4","lyric":"Lá#","duration":"eighth"},{"note":"C5","lyric":"Dó","duration":"quarter"}]', 'treble'),

-- Exercícios politonais
(86, 'Bitonalidade Dó/Fá# Maior', 'avançado', 6, 'C', '4/4', 90, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"F#4","lyric":"Fá#","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"A#4","lyric":"Lá#","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C#5","lyric":"Dó#","duration":"quarter"}]', 'treble'),

-- Compassos complexos
(87, 'Exercício em 7/8', 'avançado', 7, 'C', '7/8', 140, '[{"note":"C4","lyric":"Dó","duration":"eighth"},{"note":"D4","lyric":"Ré","duration":"eighth"},{"note":"E4","lyric":"Mi","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"A4","lyric":"Lá","duration":"eighth"},{"note":"B4","lyric":"Si","duration":"eighth"}]', 'treble'),
(88, 'Exercício em 5/4', 'avançado', 8, 'C', '5/4', 120, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"}]', 'treble'),

-- Séries dodecafônicas básicas
(89, 'Série de 12 Tons (Básica)', 'avançado', 9, 'C', '4/4', 100, '[{"note":"C4","lyric":"Dó","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"D4","lyric":"Ré","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"E4","lyric":"Mi","duration":"eighth"},{"note":"A4","lyric":"Lá","duration":"eighth"},{"note":"F#4","lyric":"Fá#","duration":"eighth"},{"note":"B4","lyric":"Si","duration":"eighth"},{"note":"G#4","lyric":"Sol#","duration":"eighth"},{"note":"C#5","lyric":"Dó#","duration":"eighth"},{"note":"A#4","lyric":"Lá#","duration":"eighth"},{"note":"D#5","lyric":"Ré#","duration":"quarter"}]', 'treble'),

-- Exercícios microtonais (aproximações)
(90, 'Quartos de Tom (Aproximação)', 'avançado', 10, 'C', '4/4', 80, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"C#4","lyric":"Dó♯","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"D#4","lyric":"Ré♯","duration":"quarter"}]', 'treble');

-- ==========================================
-- EXERCÍCIOS ESPECIAIS PARA CLAVE DE FÁ
-- ==========================================

INSERT INTO public.practice_solfege (id, title, difficulty_level, difficulty_value, key_signature, time_signature, tempo, note_sequence, clef) VALUES

(91, 'Clave de Fá - Intervalos Básicos', 'basico', 21, 'C', '4/4', 60, '[{"note":"C3","lyric":"Dó","duration":"whole"},{"note":"D3","lyric":"Ré","duration":"whole"}]', 'bass'),
(92, 'Clave de Fá - Escala de Dó', 'iniciante', 13, 'C', '4/4', 100, '[{"note":"C3","lyric":"Dó","duration":"quarter"},{"note":"D3","lyric":"Ré","duration":"quarter"},{"note":"E3","lyric":"Mi","duration":"quarter"},{"note":"F3","lyric":"Fá","duration":"quarter"},{"note":"G3","lyric":"Sol","duration":"quarter"},{"note":"A3","lyric":"Lá","duration":"quarter"},{"note":"B3","lyric":"Si","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"}]', 'bass'),
(93, 'Clave de Fá - Arpejo Maior', 'intermediário', 9, 'C', '4/4', 90, '[{"note":"C3","lyric":"Dó","duration":"quarter"},{"note":"E3","lyric":"Mi","duration":"quarter"},{"note":"G3","lyric":"Sol","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"}]', 'bass'),

-- ==========================================
-- EXERCÍCIOS ESPECIAIS PARA CLAVE DE DÓ
-- ==========================================

(94, 'Clave de Dó - Intervalos Básicos', 'iniciante', 14, 'C', '4/4', 70, '[{"note":"C4","lyric":"Dó","duration":"half"},{"note":"E4","lyric":"Mi","duration":"half"}]', 'alto'),
(95, 'Clave de Dó - Escala Básica', 'intermediário', 10, 'C', '4/4', 110, '[{"note":"C4","lyric":"Dó","duration":"eighth"},{"note":"D4","lyric":"Ré","duration":"eighth"},{"note":"E4","lyric":"Mi","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"A4","lyric":"Lá","duration":"eighth"},{"note":"B4","lyric":"Si","duration":"eighth"},{"note":"C5","lyric":"Dó","duration":"quarter"}]', 'alto');

-- ==========================================
-- Atualizar sequência para IDs automáticos
-- ==========================================
SELECT setval('practice_solfege_id_seq', (SELECT MAX(id) FROM practice_solfege) + 1);