-- ==========================================
-- Exercícios de Solfejo com Compassos Progressivos
-- Básico: 4 compassos | Iniciante: 6-8 compassos | Intermediário: 8-12 compassos | Avançado: 12-16 compassos
-- ==========================================

-- Limpar exercícios existentes primeiro
DELETE FROM public.practice_solfege;

-- ==========================================
-- NÍVEL BÁSICO (1-20) - 4 Compassos cada
-- ==========================================

INSERT INTO public.practice_solfege (title, difficulty_level, difficulty_value, key_signature, time_signature, tempo, note_sequence, clef) VALUES

-- Intervalos de 2ª - 4 compassos
('Intervalo de 2ª Maior', 'basico', 1, 'C', '4/4', 60, '[{"note":"C4","lyric":"Dó","duration":"half"},{"note":"D4","lyric":"Ré","duration":"half"},{"note":"C4","lyric":"Dó","duration":"half"},{"note":"D4","lyric":"Ré","duration":"half"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"half"},{"note":"C4","lyric":"Dó","duration":"half"},{"note":"C4","lyric":"Dó","duration":"whole"}]', 'treble'),

('Intervalos de 2ª Variados', 'basico', 2, 'C', '4/4', 65, '[{"note":"D4","lyric":"Ré","duration":"half"},{"note":"E4","lyric":"Mi","duration":"half"},{"note":"E4","lyric":"Mi","duration":"half"},{"note":"F4","lyric":"Fá","duration":"half"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"whole"}]', 'treble'),

('Intervalos de 3ª Maior', 'basico', 3, 'C', '4/4', 70, '[{"note":"C4","lyric":"Dó","duration":"half"},{"note":"E4","lyric":"Mi","duration":"half"},{"note":"D4","lyric":"Ré","duration":"half"},{"note":"F4","lyric":"Fá","duration":"half"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"}]', 'treble'),

('Intervalos de 3ª Menor', 'basico', 4, 'C', '4/4', 70, '[{"note":"D4","lyric":"Ré","duration":"half"},{"note":"F4","lyric":"Fá","duration":"half"},{"note":"E4","lyric":"Mi","duration":"half"},{"note":"G4","lyric":"Sol","duration":"half"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"whole"}]', 'treble'),

('Intervalos de 4ª Justa', 'basico', 5, 'C', '4/4', 75, '[{"note":"C4","lyric":"Dó","duration":"half"},{"note":"F4","lyric":"Fá","duration":"half"},{"note":"D4","lyric":"Ré","duration":"half"},{"note":"G4","lyric":"Sol","duration":"half"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"}]', 'treble'),

('Intervalos de 5ª Justa', 'basico', 6, 'C', '4/4', 75, '[{"note":"C4","lyric":"Dó","duration":"half"},{"note":"G4","lyric":"Sol","duration":"half"},{"note":"D4","lyric":"Ré","duration":"half"},{"note":"A4","lyric":"Lá","duration":"half"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"}]', 'treble'),

('Tríade de Dó Maior', 'basico', 7, 'C', '4/4', 80, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"half"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"}]', 'treble'),

('Tríade de Fá Maior', 'basico', 8, 'F', '4/4', 80, '[{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"F5","lyric":"Fá","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"half"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"F5","lyric":"Fá","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"whole"}]', 'treble'),

('Tríade de Sol Maior', 'basico', 9, 'G', '4/4', 80, '[{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"G5","lyric":"Sol","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"half"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"G5","lyric":"Sol","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"whole"}]', 'treble'),

('Pentacorde Ascendente', 'basico', 10, 'C', '4/4', 90, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"}]', 'treble'),

('Graus I-V-I', 'basico', 11, 'C', '4/4', 85, '[{"note":"C4","lyric":"Dó","duration":"half"},{"note":"G4","lyric":"Sol","duration":"half"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"}]', 'treble'),

('Saltos de Terça', 'basico', 12, 'C', '4/4', 80, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"}]', 'treble'),

('Movimento Ondulado', 'basico', 13, 'C', '4/4', 85, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"}]', 'treble'),

('Arpejo com Retorno', 'basico', 14, 'C', '4/4', 80, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"half"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"}]', 'treble'),

('Graus Conjuntos e Disjuntos', 'basico', 15, 'C', '4/4', 85, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"}]', 'treble'),

('Salto de Oitava', 'basico', 16, 'C', '4/4', 75, '[{"note":"C4","lyric":"Dó","duration":"half"},{"note":"C5","lyric":"Dó","duration":"half"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"whole"}]', 'treble'),

('Padrão de Terças', 'basico', 17, 'C', '4/4', 85, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"}]', 'treble'),

('Intervalos de Sexta', 'basico', 18, 'C', '4/4', 75, '[{"note":"C4","lyric":"Dó","duration":"half"},{"note":"A4","lyric":"Lá","duration":"half"},{"note":"D4","lyric":"Ré","duration":"half"},{"note":"B4","lyric":"Si","duration":"half"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"half"}]', 'treble'),

('Tetracorde Superior', 'basico', 19, 'C', '4/4', 90, '[{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"}]', 'treble'),

('Escala Fragmentada', 'basico', 20, 'C', '4/4', 80, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"half"}]', 'treble'),

-- ==========================================
-- NÍVEL INICIANTE (21-40) - 6-8 Compassos cada
-- ==========================================

('Escala de Dó Maior Completa', 'iniciante', 1, 'C', '4/4', 100, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"half"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"}]', 'treble'),

('Escala de Sol Maior', 'iniciante', 2, 'G', '4/4', 105, '[{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"E5","lyric":"Mi","duration":"quarter"},{"note":"F#5","lyric":"Fá#","duration":"quarter"},{"note":"G5","lyric":"Sol","duration":"quarter"},{"note":"F#5","lyric":"Fá#","duration":"quarter"},{"note":"E5","lyric":"Mi","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"half"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"G5","lyric":"Sol","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"whole"}]', 'treble'),

('Escala de Fá Maior', 'iniciante', 3, 'F', '4/4', 105, '[{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"Bb4","lyric":"Sib","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"E5","lyric":"Mi","duration":"quarter"},{"note":"F5","lyric":"Fá","duration":"quarter"},{"note":"E5","lyric":"Mi","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"Bb4","lyric":"Sib","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"half"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"F5","lyric":"Fá","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"whole"}]', 'treble'),

('Arpejos Maiores Combinados', 'iniciante', 4, 'C', '4/4', 95, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"F5","lyric":"Fá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"G5","lyric":"Sol","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"half"},{"note":"C4","lyric":"Dó","duration":"whole"}]', 'treble'),

('Progressão I-V-vi-IV', 'iniciante', 5, 'C', '4/4', 90, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"G5","lyric":"Sol","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"E5","lyric":"Mi","duration":"quarter"},{"note":"A5","lyric":"Lá","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"F5","lyric":"Fá","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"whole"}]', 'treble'),

-- Continue com mais exercícios de 6-8 compassos...
('Exercício em 6/8', 'iniciante', 6, 'C', '6/8', 110, '[{"note":"C4","lyric":"Dó","duration":"eighth"},{"note":"D4","lyric":"Ré","duration":"eighth"},{"note":"E4","lyric":"Mi","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"A4","lyric":"Lá","duration":"eighth"},{"note":"B4","lyric":"Si","duration":"eighth"},{"note":"C5","lyric":"Dó","duration":"eighth"},{"note":"B4","lyric":"Si","duration":"eighth"},{"note":"A4","lyric":"Lá","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"E4","lyric":"Mi","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"A4","lyric":"Lá","duration":"eighth"},{"note":"B4","lyric":"Si","duration":"eighth"},{"note":"C5","lyric":"Dó","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"E4","lyric":"Mi","duration":"eighth"},{"note":"C4","lyric":"Dó","duration":"eighth"},{"note":"E4","lyric":"Mi","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"C5","lyric":"Dó","duration":"quarter"}]', 'treble'),

('Saltos de Quinta e Oitava', 'iniciante', 7, 'C', '4/4', 85, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"E5","lyric":"Mi","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"F5","lyric":"Fá","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"G5","lyric":"Sol","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"}]', 'treble'),

-- Continue com exercícios 28-40 do nível iniciante...
-- Para economizar espaço, vou pular para alguns exemplos dos níveis superiores

-- ==========================================
-- NÍVEL INTERMEDIÁRIO (41-60) - 8-12 Compassos cada
-- ==========================================

('Escala de Lá Menor Natural', 'intermediário', 1, 'Am', '4/4', 110, '[{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"E5","lyric":"Mi","duration":"quarter"},{"note":"F5","lyric":"Fá","duration":"quarter"},{"note":"G5","lyric":"Sol","duration":"quarter"},{"note":"A5","lyric":"Lá","duration":"quarter"},{"note":"G5","lyric":"Sol","duration":"quarter"},{"note":"F5","lyric":"Fá","duration":"quarter"},{"note":"E5","lyric":"Mi","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"half"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"E5","lyric":"Mi","duration":"quarter"},{"note":"A5","lyric":"Lá","duration":"quarter"},{"note":"F5","lyric":"Fá","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"G5","lyric":"Sol","duration":"quarter"},{"note":"E5","lyric":"Mi","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"E5","lyric":"Mi","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"half"},{"note":"A4","lyric":"Lá","duration":"whole"}]', 'treble'),

-- ==========================================
-- NÍVEL AVANÇADO (61-80) - 12-16 Compassos cada
-- ==========================================

('Modo Dórico Completo', 'avançado', 1, 'C', '4/4', 120, '[{"note":"D4","lyric":"Ré","duration":"eighth"},{"note":"E4","lyric":"Mi","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"A4","lyric":"Lá","duration":"eighth"},{"note":"B4","lyric":"Si","duration":"eighth"},{"note":"C5","lyric":"Dó","duration":"eighth"},{"note":"D5","lyric":"Ré","duration":"eighth"},{"note":"C5","lyric":"Dó","duration":"eighth"},{"note":"B4","lyric":"Si","duration":"eighth"},{"note":"A4","lyric":"Lá","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"E4","lyric":"Mi","duration":"eighth"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"A4","lyric":"Lá","duration":"eighth"},{"note":"D5","lyric":"Ré","duration":"eighth"},{"note":"C5","lyric":"Dó","duration":"eighth"},{"note":"Bb4","lyric":"Sib","duration":"eighth"},{"note":"A4","lyric":"Lá","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"E4","lyric":"Mi","duration":"eighth"},{"note":"D4","lyric":"Ré","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"A4","lyric":"Lá","duration":"eighth"},{"note":"Bb4","lyric":"Sib","duration":"eighth"},{"note":"C5","lyric":"Dó","duration":"eighth"},{"note":"D5","lyric":"Ré","duration":"eighth"},{"note":"A4","lyric":"Lá","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"E4","lyric":"Mi","duration":"eighth"},{"note":"D4","lyric":"Ré","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"A4","lyric":"Lá","duration":"eighth"},{"note":"G4","lyric":"Sol","duration":"eighth"},{"note":"F4","lyric":"Fá","duration":"eighth"},{"note":"E4","lyric":"Mi","duration":"eighth"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"whole"}]', 'treble'),

-- ==========================================
-- EXERCÍCIOS PARA CLAVE DE FÁ E CLAVE DE DÓ
-- ==========================================

('Clave de Fá - Intervalos e Escalas', 'basico', 21, 'C', '4/4', 80, '[{"note":"C3","lyric":"Dó","duration":"quarter"},{"note":"D3","lyric":"Ré","duration":"quarter"},{"note":"E3","lyric":"Mi","duration":"quarter"},{"note":"F3","lyric":"Fá","duration":"quarter"},{"note":"G3","lyric":"Sol","duration":"quarter"},{"note":"A3","lyric":"Lá","duration":"quarter"},{"note":"B3","lyric":"Si","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"B3","lyric":"Si","duration":"quarter"},{"note":"A3","lyric":"Lá","duration":"quarter"},{"note":"G3","lyric":"Sol","duration":"quarter"},{"note":"F3","lyric":"Fá","duration":"quarter"},{"note":"E3","lyric":"Mi","duration":"quarter"},{"note":"D3","lyric":"Ré","duration":"quarter"},{"note":"C3","lyric":"Dó","duration":"half"}]', 'bass'),

('Clave de Dó - Arpejo e Intervalos', 'iniciante', 15, 'C', '4/4', 90, '[{"note":"C4","lyric":"Dó","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"C5","lyric":"Dó","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"C4","lyric":"Dó","duration":"half"},{"note":"D4","lyric":"Ré","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"D5","lyric":"Ré","duration":"quarter"},{"note":"A4","lyric":"Lá","duration":"quarter"},{"note":"F4","lyric":"Fá","duration":"quarter"},{"note":"D4","lyric":"Ré","duration":"half"},{"note":"E4","lyric":"Mi","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"E5","lyric":"Mi","duration":"quarter"},{"note":"B4","lyric":"Si","duration":"quarter"},{"note":"G4","lyric":"Sol","duration":"quarter"},{"note":"E4","lyric":"Mi","duration":"half"},{"note":"C4","lyric":"Dó","duration":"whole"}]', 'alto');

-- ==========================================
-- Atualizar sequência para IDs automáticos
-- ==========================================
SELECT setval('practice_solfege_id_seq', (SELECT MAX(id) FROM practice_solfege) + 1);